<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2015/08/12 10:24:00

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;port=3306;dbname=rhess',
  'username' => 'root',
  'password' => NULL,
  'attributes' => 
  array (
    'export' => 'tables',
  ),
  'name' => 'doctrine',
)),);
